from __future__ import annotations

import json
from pathlib import Path


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    if text.count(old) != 1:
        raise SystemExit(f"{path}: expected one replacement target, found {text.count(old)}")
    path.write_text(text.replace(old, new), encoding="utf-8", newline="\n")


root = Path(__import__("sys").argv[1]).resolve()

testing = root / "local_agent/tools/testing.py"
replace_once(
    testing,
    "import json\nimport re\n",
    "import hashlib\nimport json\nimport re\n",
)
replace_once(
    testing,
    '''@dataclass(frozen=True)\nclass BuildRecord:\n    """What the last successful FULL build was, and when.\n\n    Nanoseconds are kept as an integer. The old float-seconds stamp could lose\n    enough precision when converted from a filesystem timestamp that an edit\n    made immediately after a build compared equal to the build and was missed\n    on Windows CI.\n    """\n\n    profile: str\n    at_ns: int\n\n    @property\n    def at(self) -> float:\n        """Legacy seconds view for callers that only display the timestamp."""\n        return self.at_ns / 1_000_000_000\n\n\ndef touch_build_stamp(root: Any, build_dir: str, profile: str) -> None:\n''',
    '''@dataclass(frozen=True)\nclass BuildRecord:\n    """What source bytes the last successful FULL build represented.\n\n    `at_ns` remains useful audit metadata, but freshness is deliberately not a\n    clock comparison. Filesystem timestamps can compare equal across a real\n    source edit, which makes a timestamp-only proof forgeable by accident.\n    """\n\n    profile: str\n    at_ns: int\n    source_hashes: dict[str, str]\n\n    @property\n    def at(self) -> float:\n        """Legacy seconds view for callers that only display the timestamp."""\n        return self.at_ns / 1_000_000_000\n\n\ndef _source_hashes(root: Any, build_dir: str) -> dict[str, str]:\n    """Hash every build-relevant source file by canonical repository path."""\n    out: dict[str, str] = {}\n    for path in root.rglob("*"):\n        parts = path.parts\n        if build_dir in parts or ".git" in parts or ".local-agent" in parts:\n            continue\n        if path.name in (BUILD_STAMP, PROFILE_STAMP):\n            continue\n        if not path.is_file() or path.suffix.lower() not in _SOURCE_SUFFIXES:\n            continue\n        rel = path.relative_to(root).as_posix()\n        out[rel] = hashlib.sha256(path.read_bytes()).hexdigest()\n    return dict(sorted(out.items()))\n\n\ndef touch_build_stamp(root: Any, build_dir: str, profile: str) -> None:\n''',
)
replace_once(
    testing,
    '''        # Two writes on purpose. The recorded time has to come from the SAME\n        # clock as the source mtimes it will be compared against, which is the\n        # filesystem's, not `time.time()`. They agree on an ordinary local\n        # disk and can disagree on a network mount or a VM whose guest clock\n        # has drifted, and a build recorded as later than it happened would\n        # hide a real stale source.\n        #\n        # Use the integer nanosecond timestamp. `st_mtime` is a float and can\n        # collapse two nearby filesystem timestamps to the same representable\n        # value. That happened on the native Windows CI runner: an immediate\n        # source edit was not detected as stale.\n        #\n        # So: write, ask the filesystem what time it just used, then write that\n        # into the content. The second write's own mtime is a hair later than\n        # the value stored, which errs towards calling a source stale rather\n        # than fresh. That is the right direction to be wrong in.\n        stamp.write_text("{}\\n")\n        at_ns = stamp.stat().st_mtime_ns\n        stamp.write_text(json.dumps({"profile": profile, "at_ns": at_ns}) + "\\n")\n''',
    '''        # The timestamp is retained for audit/display only. The load-bearing\n        # freshness proof is the exact source-content snapshot. This makes an\n        # edit stale even when the filesystem reports the same mtime before and\n        # after it, which Windows CI demonstrated is a real case.\n        source_hashes = _source_hashes(root, build_dir)\n        stamp.write_text("{}\\n", encoding="utf-8")\n        at_ns = stamp.stat().st_mtime_ns\n        stamp.write_text(\n            json.dumps({\n                "profile": profile,\n                "at_ns": at_ns,\n                "source_hashes": source_hashes,\n            }, sort_keys=True) + "\\n",\n            encoding="utf-8",\n        )\n''',
)
replace_once(
    testing,
    '''        payload = json.loads(text)\n        profile = payload.get("profile")\n        at_ns = payload.get("at_ns")\n        # Read stamps produced by the previous package. They carried float\n        # seconds. New writes are always nanoseconds, so precision is never\n        # thrown away again after this point.\n        if at_ns is None and isinstance(payload.get("at"), (int, float)):\n            at_ns = int(float(payload["at"]) * 1_000_000_000)\n    except (ValueError, AttributeError):\n        return None  # legacy "ok\\n" stamp: built, but by whom, when, for what?\n\n    # The time comes out of the CONTENT, never from the file's mtime.\n    #\n    # Reading the mtime made the stamp forgeable by touching it, and touching a\n    # file inside the repository was a tool call the model already had:\n    # propose_patch a byte, apply_patch, and the staleness baseline jumped to\n    # now with nothing compiled. Writes into the build directory are refused\n    # outright as well, and these are two independent locks on the same door\n    # because that door decides whether a result counts as proof.\n    if not isinstance(at_ns, int) or at_ns <= 0:\n        return None\n    if not isinstance(profile, str) or not profile:\n        return None\n    return BuildRecord(profile=profile, at_ns=at_ns)\n''',
    '''        payload = json.loads(text)\n        profile = payload.get("profile")\n        at_ns = payload.get("at_ns")\n        source_hashes = payload.get("source_hashes")\n    except (ValueError, AttributeError):\n        return None  # legacy "ok\\n" stamp: built, but by whom, when, for what?\n\n    # A timestamp-only stamp is no longer trusted. It cannot establish which\n    # bytes were compiled, so an older checkout must perform one fresh full\n    # build before its tests can count as proof.\n    if not isinstance(at_ns, int) or at_ns <= 0:\n        return None\n    if not isinstance(profile, str) or not profile:\n        return None\n    if not isinstance(source_hashes, dict) or not all(\n        isinstance(path, str)\n        and isinstance(digest, str)\n        and len(digest) == 64\n        for path, digest in source_hashes.items()\n    ):\n        return None\n    return BuildRecord(profile=profile, at_ns=at_ns, source_hashes=source_hashes)\n''',
)
start = testing.read_text(encoding="utf-8")
old = '''def _stale_sources(root: Any, build_dir: str, record: BuildRecord | None) -> list[str]:\n    """Source files modified since the build directory was last written.\n\n    ctest does not build. A model that edits a source file and reruns the test\n    gets the previous binary's result, identical to the one before the edit,\n    and no amount of rereading the source explains why. The 30B spent ten tool\n    calls on exactly that: it fixed the defect correctly, reran, saw the same\n    failure, checked the file, saw its own correct fix, and looped until the\n    repeat guard stopped it.\n\n    So the tool says it. Deterministically, from mtimes, with no guessing.\n    """\n    if record is None:\n        # No successful full build recorded, so there is nothing to compare\n        # mtimes against. This is NOT "nothing is stale": it is "freshness is\n        # unknown", and the caller reports it as its own invalidating\n        # condition. Returning [] here and letting the result stand as a PASS\n        # is precisely how an unbuilt profile verified old binaries.\n        return []\n    newest_build_ns = record.at_ns\n\n    stale: list[str] = []\n    for path in root.rglob("*"):\n        parts = path.parts\n        if build_dir in parts or ".git" in parts or ".local-agent" in parts:\n            continue\n        if path.name in (BUILD_STAMP, PROFILE_STAMP):\n            continue\n        if not path.is_file() or path.suffix.lower() not in _SOURCE_SUFFIXES:\n            continue\n        try:\n            if path.stat().st_mtime_ns > newest_build_ns:\n                # Evidence is serialized and shown to the model. Repository\n                # paths therefore have one canonical spelling on every host,\n                # not backslashes on Windows and slashes on Linux.\n                stale.append(path.relative_to(root).as_posix())\n        except OSError:  # pragma: no cover\n            continue\n    return sorted(stale)\n'''
new = '''def _stale_sources(root: Any, build_dir: str, record: BuildRecord | None) -> list[str]:\n    """Source paths whose current bytes differ from the last full build.\n\n    ctest does not build. Freshness therefore has to be a content statement,\n    not a clock statement: equal mtimes must never make changed source look\n    represented by an older binary. Added and deleted build inputs are stale\n    for the same reason as modified ones.\n    """\n    if record is None:\n        # No content-bound successful full build is recorded. This is NOT\n        # "nothing is stale": the caller reports unknown build provenance as\n        # its own invalidating condition.\n        return []\n\n    current = _source_hashes(root, build_dir)\n    names = set(record.source_hashes) | set(current)\n    return sorted(\n        name for name in names\n        if record.source_hashes.get(name) != current.get(name)\n    )\n'''
if start.count(old) != 1:
    raise SystemExit(f"{testing}: stale-source block mismatch ({start.count(old)})")
testing.write_text(start.replace(old, new), encoding="utf-8", newline="\n")

build = root / "local_agent/tools/build.py"
replace_once(
    build,
    '''            # The only thing in the tree that says "a compile succeeded at this\n            # moment". run_test compares source mtimes against it.\n            #\n            # The obvious alternative, the newest mtime anywhere under build/,\n            # is wrong: ctest writes build/Testing/LastTest.log every time it\n            # runs, so editing a source and then running the tests twice made\n            # the staleness warning vanish with nothing recompiled. A timestamp\n            # written by the test runner is not evidence of a build.\n''',
    '''            # The stamp binds a successful full compile to the exact source\n            # bytes present when it completed. run_test compares content hashes,\n            # never filesystem clocks, so an equal-mtime edit cannot make stale\n            # binaries look current. Test-runner timestamps are irrelevant.\n''',
)

compat = root / "measurement/run_test_suite.py"
replace_once(
    compat,
    '''    def setenv(self, name: str, value: str) -> None:\n        old = os.environ.get(name)\n        self._undo.append(\n            lambda: os.environ.pop(name) if old is None else os.environ.__setitem__(name, old)\n        )\n        os.environ[name] = value\n\n    def undo(self) -> None:\n''',
    '''    def setenv(self, name: str, value: str) -> None:\n        old = os.environ.get(name)\n        self._undo.append(\n            lambda: os.environ.pop(name, None) if old is None else os.environ.__setitem__(name, old)\n        )\n        os.environ[name] = value\n\n    def delenv(self, name: str, raising: bool = True) -> None:\n        if name not in os.environ:\n            if raising:\n                raise KeyError(name)\n            return\n        old = os.environ[name]\n        self._undo.append(lambda: os.environ.__setitem__(name, old))\n        del os.environ[name]\n\n    def undo(self) -> None:\n''',
)

cross = root / "tests/unit/test_cross_platform_evidence.py"
cross.write_text('''"""Fast regressions for cross-platform build evidence representation."""\n\nfrom __future__ import annotations\n\nimport hashlib\nimport json\nimport os\nfrom pathlib import Path\n\nfrom local_agent.tools.testing import BuildRecord, _stale_sources, build_record\n\n\ndef _sha(data: bytes) -> str:\n    return hashlib.sha256(data).hexdigest()\n\n\ndef test_stale_source_paths_are_canonical_repository_paths(tmp_path: Path):\n    source = tmp_path / "src" / "nested" / "thing.cpp"\n    source.parent.mkdir(parents=True)\n    source.write_text("int x;\\n", encoding="utf-8")\n\n    record = BuildRecord(\n        profile="debug", at_ns=1,\n        source_hashes={"src/nested/thing.cpp": _sha(b"int y;\\n")},\n    )\n    assert _stale_sources(tmp_path, "build", record) == ["src/nested/thing.cpp"]\n\n\ndef test_staleness_is_content_based_even_when_mtime_is_identical(tmp_path: Path):\n    source = tmp_path / "src" / "thing.cpp"\n    source.parent.mkdir(parents=True)\n    source.write_text("int before;\\n", encoding="utf-8")\n    stat = source.stat()\n    record = BuildRecord(\n        profile="debug", at_ns=stat.st_mtime_ns,\n        source_hashes={"src/thing.cpp": _sha(source.read_bytes())},\n    )\n\n    source.write_text("int after;\\n", encoding="utf-8")\n    os.utime(source, ns=(stat.st_atime_ns, stat.st_mtime_ns))\n\n    assert source.stat().st_mtime_ns == stat.st_mtime_ns\n    assert _stale_sources(tmp_path, "build", record) == ["src/thing.cpp"]\n\n\ndef test_build_record_preserves_content_snapshot(tmp_path: Path):\n    build = tmp_path / "build"\n    build.mkdir()\n    stamp = build / ".local-agent-build-ok"\n    stamp.write_text(\n        json.dumps({\n            "profile": "debug",\n            "at_ns": 1_234_567_890_123_456_789,\n            "source_hashes": {"src/x.cpp": "a" * 64},\n        }),\n        encoding="utf-8",\n    )\n\n    record = build_record(tmp_path, "build")\n    assert record is not None\n    assert record.profile == "debug"\n    assert record.at_ns == 1_234_567_890_123_456_789\n    assert record.source_hashes == {"src/x.cpp": "a" * 64}\n\n\ndef test_timestamp_only_legacy_stamp_is_unknown_provenance(tmp_path: Path):\n    build = tmp_path / "build"\n    build.mkdir()\n    stamp = build / ".local-agent-build-ok"\n    stamp.write_text(\n        json.dumps({"profile": "debug", "at_ns": 1_234_567_890}),\n        encoding="utf-8",\n    )\n\n    assert build_record(tmp_path, "build") is None\n''', encoding="utf-8", newline="\n")

integration = root / "tests/integration/test_evaluator_cannot_be_fooled.py"
replace_once(
    integration,
    '''    source = root / "src" / "ring_buffer.cpp"\n    source.write_text(source.read_text() + "\\n// edited, not rebuilt\\n")\n    assert registry.get("run_test").handler().data["stale_sources"] == ["src/ring_buffer.cpp"]\n''',
    '''    source = root / "src" / "ring_buffer.cpp"\n    original = source.stat()\n    source.write_text(source.read_text() + "\\n// edited, not rebuilt\\n")\n    # Make the timestamp actively unhelpful. Content binding must still catch\n    # the edit; sleeps/tolerances/mtime nudges are not accepted fixes.\n    import os\n    os.utime(source, ns=(original.st_atime_ns, original.st_mtime_ns))\n    assert source.stat().st_mtime_ns == original.st_mtime_ns\n    assert registry.get("run_test").handler().data["stale_sources"] == ["src/ring_buffer.cpp"]\n''',
)
replace_once(
    integration,
    '''    after = build_record(root, "build")\n    assert after is not None and after.at == before.at, \\\n        "touching the stamp must not move the baseline"\n''',
    '''    after = build_record(root, "build")\n    assert before is not None and after is not None\n    assert after.at == before.at, "touching the stamp must not move the audit time"\n    assert after.source_hashes == before.source_hashes, \\\n        "touching the stamp must not move the content baseline"\n''',
)

print("phase2 CI blocker fixes applied")
